apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: micros-deployment
  labels:
    app: micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micros
  template:
    metadata:
      labels:
        app: micros
    spec:
      containers:
      - name: signup
        image: wjstk16/micros:0.1
        ports:
        - containerPort: 10050
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "356Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      nodeSelector:
        hostname: signup

          
