apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: microsea-deployment
  labels:
    app: microsea
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microsea
  template:
    metadata:
      labels:
        app: microsea
    spec:
      containers:
      - name: search
        image: wjstk16/microsea:0.2
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "356Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      nodeSelector:
        hostname: search
          
