apiVersion: v1
kind: Service
metadata:
  name: microe-service
spec:
  ports:
    - name: "editproduct"
      port: 5000
      targetPort: 5000
      nodePort: 31114
  selector:
    app: microe
  type: NodePort
