apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: microe-deployment
  labels:
    app: microe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microe
  template:
    metadata:
      labels:
        app: microe
    spec:
      containers:
      - name: editproduct
        image: wjstk16/microe
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "356Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      nodeSelector:
        hostname: editproduct
          
