apiVersion: v1
kind: Service
metadata:
  name: microg-service
spec:
  ports:
    - name: "getlist"
      port: 5000
      targetPort: 5000
      nodePort: 31116
  selector:
    app: microg
  type: NodePort
