apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: microl-deployment
  labels:
    app: microl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microl
  template:
    metadata:
      labels:
        app: microl
    spec:
      containers:
      - name: login
        image: wjstk16/microl:0.2
        ports:
        - containerPort: 5000
          name: flask
        - containerPort: 32222
          name: zabbix
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "356Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      nodeSelector:
        hostname: login
          
