apiVersion: v1
kind: Service
metadata:
  name: micros-service
spec:
  ports:
    - name: "signup"
      port: 5000
      targetPort: 5000
      nodePort: 31112
       
  selector:
    app: micros
  type: NodePort
