apiVersion: v1
kind: Service
metadata:
  name: microl-service
spec:
  ports:
    - name: "login"
      port: 5000
      targetPort: 5000
      nodePort: 31113
  
  selector:
    app: microl
  type: NodePort
